stages:
  - test

variables:
  DOCKER_DRIVER: overlay2

# Этап тестирования
test:
  stage: test
  script:
    - docker build -t test-project .
    - docker run --name test-container test-project
    - docker exec test-container pytest --alluredir=/app/allure-results
  when: manual
  allow_failure: false
  tags:
    - docker